# Use the official ASP.NET runtime as a base image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
ARG ASPNETCORE_ENVIRONMENT=Staging
ENV ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
WORKDIR /app
EXPOSE 80

# Use the SDK image for building the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG ASPNETCORE_ENVIRONMENT=Staging
ENV ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
WORKDIR /src

# Copy the project files to the container. 
# Make sure to include the correct path to your backend project directory.
COPY ./backend.csproj ./
RUN dotnet restore

# Copy the rest of the backend files
COPY ./ ./

# Build the application
RUN dotnet build "backend.csproj" -c Release -o /app/build \
    --no-restore \
    /p:EnvironmentName=${ASPNETCORE_ENVIRONMENT}

# Publish the application
FROM build AS publish
ARG ASPNETCORE_ENVIRONMENT=Staging
ENV ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
RUN dotnet publish "backend.csproj" -c Release -o /app/publish \
    --no-restore \
    /p:EnvironmentName=${ASPNETCORE_ENVIRONMENT}

# Final image: copy the published application and set the entry point
FROM base AS final
ARG ASPNETCORE_ENVIRONMENT=Staging
ENV ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
WORKDIR /app
COPY --from=publish /app/publish .
COPY ./Resources /app/Resources

ENV ASPNETCORE_ENVIRONMENT "Staging"

ENTRYPOINT ["dotnet", "backend.dll", "--environment=Staging"]

