import { FamilyUserInterface } from "../Api/apiInterface";

export const mockFamilyUsers: FamilyUserInterface[] = [
  {
    userId: 1,
    userNickName: 'JohnSmith',
    familyId: 100,
    familyRole: 'Leader',
    isApproved: true,
    avatarColor: '#FFD700',
    avatarUrl: 'https://example.com/avatar1.png',
    avatarFgColor: '#000000',
  },
  {
    userId: 2,
    userNickName: 'JaneDoe',
    familyId: 100,
    familyRole: 'Cook',
    isApproved: true,
    avatarColor: '#FF69B4',
    avatarUrl: 'https://example.com/avatar2.png',
    avatarFgColor: '#FFFFFF',
  },
  {
    userId: 3,
    userNickName: 'Jimmy',
    familyId: 100,
    familyRole: 'Eater',
    isApproved: false,
    avatarColor: '#ADD8E6',
    avatarUrl: 'https://example.com/avatar3.png',
    avatarFgColor: '#000000',
  },
  {
    userId: 4,
    userNickName: 'AliceJ',
    familyId: 200,
    familyRole: 'Grocery Shopper',
    isApproved: true,
    avatarColor: '#90EE90',
    avatarUrl: 'https://example.com/avatar4.png',
    avatarFgColor: '#000000',
  },
  {
    userId: 5,
    userNickName: 'BobJ',
    familyId: 200,
    familyRole: 'Member',
    isApproved: false,
    avatarColor: '#FFB6C1',
    avatarUrl: 'https://example.com/avatar5.png',
    avatarFgColor: '#FFFFFF',
  },
  {
    userId: 6,
    userNickName: 'CharlieB',
    familyId: 300,
    familyRole: 'Cook',
    isApproved: true,
    avatarColor: '#D3D3D3',
    avatarUrl: 'https://example.com/avatar6.png',
    avatarFgColor: '#000000',
  },
];