name: Development

on:
  push:
    branches: development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 1. Print environment variables
      run: printenv
    - uses: actions/checkout@v4
    
    - name: 2. Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore backend dependencies
      run: dotnet restore backend/backend.csproj
      
    - name: 3. Build backend
      run:  dotnet build backend/backend.csproj
      
    - name: 4. Run backend tests
      env:  
        ImgBB_API_Key: ${{ secrets.ImgBB_API_Key }}
        DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING}}
      run: 
        dotnet test backend.Tests/backend.Tests.csproj
        
    - name: 5. Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 6. Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}  
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}  

    - name: 7. Build Docker image
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}
        docker build -t ${{ secrets.DOCKER_HUB_USER }}/family-meal-planner-backend:${IMAGE_TAG} -f backend/DockerFile backend/

    - name: 8. Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USER }}/family-meal-planner-backend:${IMAGE_TAG}
    
    - name: 10. Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: image_tag
        path: image_tag.txt

    - name: 11. Create Docker tag file
      run: echo ${{ IMAGE_TAG }} > image_tag.txt
