name: Build and Push Docker image

on:
  push:
    branches:
      - staging  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code from the GitHub repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (Optional if you need advanced build features)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER_STAGING }}  
        password: ${{ secrets.DOCKER_HUB_PASSWORD_STAGING }}  

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USER_STAGING }}/family-meal-planner-backend-staging:latest -f backend/DockerFile backend/

    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_HUB_USER_STAGING }}/family-meal-planner-backend-staging:latest

    # Step 6: Deploy Docker image to Render
    - name: Trigger Render Deployment
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY_STAGING }}  
      run: |
        # Trigger deployment to Render
        curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_STAGING }} \
        -H "Authorization: Bearer $RENDER_API_KEY_STAGING" \
        -H "Content-Type: application/json" \
        -d '{"branch": "staging"}'  

    # Step 7: Navigate to the backend folder
      - name: Navigate to backend folder
        run: cd backend  

    # Step 8: Set up .NET Core environment
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  

    # Step 9: Install EF Core CLI
    - name: Install EF Core CLI
      run: dotnet tool install --global dotnet-ef

    # Step 10: Build the backend project
    - name: Build the backend
      run: dotnet build --configuration Release

    # Step 11: Run EF Core database update
    - name: Run EF Core Migrations
      env:
        ConnectionStrings_DefaultConnection: ${{ secrets.CONNECTION_STRINGS }}
        SendGrid_Email: ${{ secrets.SENDGRID_EMAIL }}
        SendGrid_API_Key: ${{ secrets.SENDGRID_API_KEY }}
        OpenAI_API_Key: ${{ secrets.OPENAI_API_KEY }}
        ImgBB_API_Key: ${{ secrets.IMGBB_API_KEY }}
        JWT_Issuer: ${{ secrets.JWT_ISSUER }}
        JWT_Audience: ${{ secrets.JWT_AUDIENCE }}
        JWT_AppName: ${{ secrets.JWT_APPNAME }}
        JWT_RefreshTokenName: ${{ secrets.JWT_REFRESHTOKENNAME }}
        JWT_Secret: ${{ secrets.JWT_SECRET }}
      run: |
        dotnet ef database update --project backend/backend.csproj --context FamilyMealPlannerContext
