name: Staging

on:
  push:
    branches: staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print environment variables
        run: printenv

      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Restore backend dependencies
        run: dotnet restore backend/backend.csproj

      - name: Build backend
        run: dotnet build backend/backend.csproj -c Release

      - name: Run backend tests
        env:
          ImgBB_API_Key: ${{ secrets.ImgBB_API_Key }}
          DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
        run: dotnet test backend.Tests/backend.Tests.csproj

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/family-meal-planner-backend:staging -f backend/DockerFile backend/
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USER }}/family-meal-planner-backend:staging
      - name: Trigger Render Deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY_STAGING }}
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_STAGING }} \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"branch": "staging"}'
      - name: Wait for deployment
        run: |
          echo "Waiting 120 seconds for deployment to stabilize..."
          sleep 120
      - name: Run EF Core Migrations
        env:
          ConnectionStrings_DefaultConnection: ${{ secrets.CONNECTION_STRINGS_STAGING }}
          PATH: $PATH:/home/runner/.dotnet/tools  
        run: |
          dotnet ef database update --project backend/backend.csproj --context FamilyMealPlannerContext